
# classic oldies mix 1
curl --request GET \
  --output classic_oldies_mix1.json \
  --url https://api.spotify.com/v1/playlists/23GrhDv3NZlyaqo2ayGXkm \
  --header 'Authorization: Bearer BQBaFghp3PWMwTadoTrmEFmBqkXs-dcTc59yj3R-HoMhYIVJMhZpLycqrov5LxTl6iZMW3ExXei5dcrY1cwUZb5CyMEzuW17Ullyb0QLBkLddabLeiY'

# classic oldies 2
curl --request GET \
  --output classic_oldies2.json \
  --url https://api.spotify.com/v1/playlists/37i9dQZF1DX56bqlsMxJYR \
  --header 'Authorization: Bearer BQBaFghp3PWMwTadoTrmEFmBqkXs-dcTc59yj3R-HoMhYIVJMhZpLycqrov5LxTl6iZMW3ExXei5dcrY1cwUZb5CyMEzuW17Ullyb0QLBkLddabLeiY'

# 80s party
curl --request GET \
  --output the80s_party.json \
  --url https://api.spotify.com/v1/playlists/37i9dQZF1DX6xnkAwJX7tn \
  --header 'Authorization: Bearer BQBaFghp3PWMwTadoTrmEFmBqkXs-dcTc59yj3R-HoMhYIVJMhZpLycqrov5LxTl6iZMW3ExXei5dcrY1cwUZb5CyMEzuW17Ullyb0QLBkLddabLeiY'

# Best of 70s and 80s
curl --request GET \
  --output best70s80s.json \
  --url https://api.spotify.com/v1/playlists/1nZpLA56VbyXsEG2VqRonU \
  --header 'Authorization: Bearer BQBaFghp3PWMwTadoTrmEFmBqkXs-dcTc59yj3R-HoMhYIVJMhZpLycqrov5LxTl6iZMW3ExXei5dcrY1cwUZb5CyMEzuW17Ullyb0QLBkLddabLeiY'

# 90s hits
curl --request GET \
  --output the90s_hits.json \
  --url https://api.spotify.com/v1/playlists/3C64V048fGyQfCjmu9TIGA \
  --header 'Authorization: Bearer BQBaFghp3PWMwTadoTrmEFmBqkXs-dcTc59yj3R-HoMhYIVJMhZpLycqrov5LxTl6iZMW3ExXei5dcrY1cwUZb5CyMEzuW17Ullyb0QLBkLddabLeiY'
