curl -X POST "https://accounts.spotify.com/api/token" ^
     -H "Content-Type: application/x-www-form-urlencoded" ^
     -d "grant_type=client_credentials&client_id=f4f54a850da14f27a6e2b44603fe8013&client_secret=4f00203d797d42ffb03d023272f084c3"