

curl --request GET ^
  --output the00s_1.json ^
  --url https://api.spotify.com/v1/playlists/37i9dQZF1DWVL8L5hAi6Qc ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"


curl --request GET ^
  --output the00s_2.json ^
  --url https://api.spotify.com/v1/playlists/5bJpt3ljc9uSWiIV1pY6pz ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"


curl --request GET ^
  --output the00s_3.json ^
  --url https://api.spotify.com/v1/playlists/0y6Bq4RldIeYeHzMSOPmtf ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"


curl --request GET ^
  --output the00s_4.json ^
  --url https://api.spotify.com/v1/playlists/4eJt1mDmFWADM3T0zEUA48 ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"


curl --request GET ^
  --output the00s_5.json ^
  --url https://api.spotify.com/v1/playlists/0yxJFChaPf458Sub9qW9P5 ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"


curl --request GET ^
  --output the00s_6.json ^
  --url https://api.spotify.com/v1/playlists/1Ay29GfWbRACv5x0dve3HK ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"



curl --request GET ^
  --output the90s_1.json ^
  --url https://api.spotify.com/v1/playlists/37i9dQZF1DXaLI8a395lse ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"




curl --request GET ^
  --output the90s_2.json ^
  --url https://api.spotify.com/v1/playlists/7n9o9hO5buU4ngv6tpsaTC ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"




curl --request GET ^
  --output the90s_3.json ^
  --url https://api.spotify.com/v1/playlists/37i9dQZF1DWVpjAJGB70vU ^
  --header "Authorization: Bearer BQCXpfRHcnBA0ziuvOhVokevR-sBtc36GGGj6HHhdQSVDSeW5QQ9rPcKOfVft0oAKwald6BxUJ-u1WWyphvz20ShMbnX_qjg6O6hVAfpMrwYimQg2Ls"

